# 내가 뭔가를 쓰고 싶을때 변수 처럼 쓴다.
#server:
#  port: 8083

jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}

project:
  upload:
    path: ${UPLOAD_PATH}
  aes:
    #32 바이트 (32글자 여야 한다.)
    key: aessecretkey12345678912345678900


management:
  # 프로메테우스 설정
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

  # jaeger 설정
  tracing:
#    enabled: false # 프로메테우스를 위해 설정, 메트릭을 Prometheus가 읽지 못하는 에러 해결
    sampling:
      probability: 1.0  # 모든 요청에 대한 데이터 수집
  otlp:
    tracing:
      endpoint: "http://192.168.23.20:4318/v1/traces" # Jaeger 수집 주소

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            # 카카오 로그인하기 할때, 따로 설정을 해야 됨
            authorization-grant-type: authorization_code
              # 어떤걸 받아 갈 건지
            scope: profile_nickname
            client-authentication-method: client_secret_post
            # 설정을 어떻게 받아 갈거야
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  application:
    name: spring04

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${S3_bucket}
      region:
        static: ap-northeast-2

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDR}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.example.demo: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace